### ISSUE TITLE
peeker enhancments

### ISSUE THREAD

**Issue by GProtoZeroW** [devbisme/myhdlpeek#2]
Love Peeker for myHDL. But 
1. what is the lib that is doing the waveform plotting
2. Is there possibly a way to add a jupyter notebook widget to then scrub threw the waveform timeline
3. Can you add a method that ports the json to pandas? I have tried to write this but it has not been reliable

When I am doing DSP 3 is the most important thanks

**Comment by xesscorp** [comment]
1. The javascript library that does the plotting is from http://wavedrom.com/wavedrom.min.js.
2. You would need to create two windows: one that holds the signal names and a second that is horizontally scrollable to display the waveforms. Thought about it, but haven't done it.
3. Do you want to port the wavedrom json to pandas? Or do you want to load a pandas dataframe with the signal names and values?

**Comment by GProtoZeroW** [comment]
Thanks. I will play with. And the priority would be Json->Pandas, but the other way would be nice to

**Comment by xesscorp** [comment]
My question is actually about what you want to do with the wavejson data. It's just a Python structure with a bunch of information that's pretty specific to wavedrom: it records the signal values in a weird format along with other parameters that affect the display. Is that something you want to try to manipulate in pandas? Or do you want to work with the waveform values, in which case an array-like data structure would do.

**Comment by GProtoZeroW** [comment]
have each signal that is bound to  Peeker be a column, and each timestep set to a row. 

So, for example, I have an FIR filter that I hit with a step response. I run the TB then bind the Peeker Pandas Dataframe output to a new var. Then I can ask it where clk ==True and take that subset apply a Z transform to the input and output columns in new columns and then do a divide of those columns and see if I actually got my filter implementation right.  
Or if I am doing a state machine I have a pure python one in place and recorded it into a dataframe and then I take the myHDL -> peeker resulting dataframe and do a direct compersion (after some manipulation) and go Yeah or ERRRRRRRRRG!

And I have tried doing this myself by trying to import the JSON to pandas but I can never get it to work proprly.

**Comment by xesscorp** [comment]
OK, that doesn't sound too hard to do. It's similar to outputting the data as a table. No need to try to interpret the JSON-formatted data. I'll look into it.

**Comment by xesscorp** [comment]
I created a new branch called 'pandas'. It contains the `to_dataframe()` method for exporting a Peeker to a Pandas DataFrame. Try it out and let me know if it works for what you want.

    @classmethod
    def to_dataframe(cls, *names, **kwargs):
        '''
        Convert traces stored in peekers into a Pandas DataFrame of times and trace values.

        Args:
            *names: A list of strings containing the names for the Peekers that
                will be processed. A string may contain multiple,
                space-separated names.

        Keywords Args:
            start_time: The earliest (left-most) time bound for the traces.
            stop_time: The latest (right-most) time bound for the traces.
            step: Set the time increment for filling in between sample times.
                If 0, then don't fill in between sample times.

        Returns:
            A DataFrame with the columns for the named traces and time as the index.
        '''
